var SHADERS = (function () {
  'use strict';

  var VERT = [
    '#version 300 es',
    'in vec2 aPos;',
    'void main(){ gl_Position = vec4(aPos, 0.0, 1.0); }'
  ].join('\n');

  /*
   * Compiled twice. In DEEP mode every coordinate is a double-float (an unevaluated
   * hi+lo pair of float32s, ~48 bits of mantissa), which is what lets the cell structure
   * survive deep zooms: plain float32 starts misclassifying cells at a pixel size of 1e-6.
   */
  function frag(deep) {
    return [
    '#version 300 es',
    deep ? '#define DEEP 1' : '',
    'precision highp float;',
    'precision highp int;',
    'out vec4 fragColor;',
    '',
    '#define MAXV 16',
    'uniform vec2  uKVerts[MAXV];  // Klein coordinates (CCW)',
    'uniform vec2  uKVertsLo[MAXV];',
    'uniform vec3  uHVerts[MAXV];  // unit hyperboloid coordinates (Euclidean model: xy only)',
    'uniform vec3  uHVertsLo[MAXV];',
    'uniform int   uN;',
    'uniform int   uGeom;          // 0 = Poincare disk, 1 = Euclidean plane',
    'uniform int   uIters;',
    'uniform int   uMode;',
    'uniform int   uStepPick;',
    'uniform int   uSS;',
    'uniform vec2  uCenter;',
    'uniform vec2  uCenterLo;',
    'uniform float uScale;         // disk units per device pixel',
    'uniform vec2  uResolution;',
    'uniform float uHueShift;',
    'uniform float uCScale;',
    'uniform float uSat;',
    'uniform float uVal;',
    'uniform float uEps;',
    'uniform float uGlow;         // singular-set glow intensity',
    'uniform float uGlowW;        // glow width, in hyperbolic units',
    'uniform float uShade;        // within-cell gradient strength',
    'uniform float uShadeScale;',
    'uniform vec2  uJitter;        // sub-pixel offset of this pass',
    'uniform vec3  uBg;',
    'uniform vec3  uTable;',
    '',
    '#ifdef DEEP',
    '// unevaluated sums: value = hi + lo',
    'vec2 dsAdd(vec2 a, vec2 b){',
    '  float s = a.x + b.x;',
    '  float v = s - a.x;',
    '  float e = (a.x - (s - v)) + (b.x - v);',
    '  float t = e + (a.y + b.y);',
    '  float hi = s + t;',
    '  return vec2(hi, t - (hi - s));',
    '}',
    'vec2 dsMul(vec2 a, vec2 b){',
    '  const float SPLIT = 4097.0;   // 2^12 + 1, splits a 24-bit mantissa in half',
    '  float ca = SPLIT * a.x, cb = SPLIT * b.x;',
    '  float ahi = ca - (ca - a.x), bhi = cb - (cb - b.x);',
    '  float alo = a.x - ahi,       blo = b.x - bhi;',
    '  float p = a.x * b.x;',
    '  float err = ((ahi*bhi - p) + ahi*blo + alo*bhi) + alo*blo;',
    '  float t = err + (a.x*b.y + a.y*b.x);',
    '  float hi = p + t;',
    '  return vec2(hi, t - (hi - p));',
    '}',
    'vec2 dsDiv(vec2 a, vec2 b){',
    '  float s = a.x / b.x;',
    '  vec2 r = dsAdd(a, -dsMul(vec2(s, 0.0), b));',
    '  float t = (r.x + r.y) / b.x;',
    '  float hi = s + t;',
    '  return vec2(hi, t - (hi - s));',
    '}',
    'bool dsLtZero(vec2 a){ return a.x < 0.0 || (a.x == 0.0 && a.y < 0.0); }',
    '#define REAL      vec2',
    '#define RC(x)     vec2(x, 0.0)',
    '#define RADD(a,b) dsAdd(a, b)',
    '#define RSUB(a,b) dsAdd(a, -(b))',
    '#define RMUL(a,b) dsMul(a, b)',
    '#define RDIV(a,b) dsDiv(a, b)',
    '#define RNEG(a)   (-(a))',
    '#define RF(a)     ((a).x + (a).y)',
    '#define RLT0(a)   dsLtZero(a)',
    '#else',
    '#define REAL      float',
    '#define RC(x)     (x)',
    '#define RADD(a,b) ((a) + (b))',
    '#define RSUB(a,b) ((a) - (b))',
    '#define RMUL(a,b) ((a) * (b))',
    '#define RDIV(a,b) ((a) / (b))',
    '#define RNEG(a)   (-(a))',
    '#define RF(a)     (a)',
    '#define RLT0(a)   ((a) < 0.0)',
    '#endif',
    '',
    'struct P2 { REAL x; REAL y; };',
    'struct P3 { REAL x; REAL y; REAL z; };',
    '',
    'P2 kvert(int i){',
    '#ifdef DEEP',
    '  return P2(vec2(uKVerts[i].x, uKVertsLo[i].x), vec2(uKVerts[i].y, uKVertsLo[i].y));',
    '#else',
    '  return P2(uKVerts[i].x, uKVerts[i].y);',
    '#endif',
    '}',
    'P3 hvert(int i){',
    '#ifdef DEEP',
    '  return P3(vec2(uHVerts[i].x, uHVertsLo[i].x), vec2(uHVerts[i].y, uHVertsLo[i].y),',
    '            vec2(uHVerts[i].z, uHVertsLo[i].z));',
    '#else',
    '  return P3(uHVerts[i].x, uHVerts[i].y, uHVerts[i].z);',
    '#endif',
    '}',
    'P2 pixelPoint(vec2 p){',
    '  vec2 off = (p - 0.5 * uResolution) * uScale;',
    '#ifdef DEEP',
    '  return P2(dsAdd(vec2(uCenter.x, uCenterLo.x), vec2(off.x, 0.0)),',
    '            dsAdd(vec2(uCenter.y, uCenterLo.y), vec2(off.y, 0.0)));',
    '#else',
    '  return P2(uCenter.x + off.x, uCenter.y + off.y);',
    '#endif',
    '}',
    'vec2 toF(P2 p){ return vec2(RF(p.x), RF(p.y)); }',
    'P2 subP(P2 a, P2 b){ return P2(RSUB(a.x, b.x), RSUB(a.y, b.y)); }',
    'REAL crsP(P2 a, P2 b){ return RSUB(RMUL(a.x, b.y), RMUL(a.y, b.x)); }',
    '',
    'vec2 toKlein(vec2 z){ return 2.0*z / (1.0 + dot(z,z)); }',
    'float crs(vec2 a, vec2 b){ return a.x*b.y - a.y*b.x; }',
    '',
    'vec3 hsv2rgb(vec3 c){',
    '  vec3 p = abs(fract(c.xxx + vec3(1.0, 2.0/3.0, 1.0/3.0)) * 6.0 - 3.0);',
    '  return c.z * mix(vec3(1.0), clamp(p - 1.0, 0.0, 1.0), c.y);',
    '}',
    '',
    '// Klein projection: identity in the Euclidean model',
    'P2 proj(P2 z){',
    '  if (uGeom != 0) return z;',
    '  REAL q = RADD(RC(1.0), RADD(RMUL(z.x, z.x), RMUL(z.y, z.y)));',
    '  return P2(RDIV(RADD(z.x, z.x), q), RDIV(RADD(z.y, z.y), q));',
    '}',
    '',
    '// One step of the outer billiard map, in Klein coordinates.',
    '// Hyperbolic: the point reflection is the linear Lorentz map X -> -(X + 2<X,V>V) on the',
    '// hyperboloid, carried projectively as (k, 1). Being division-free it avoids the ruinous',
    '// cancellation of the Poincare formula, where 1-|z| underflows after ~20 escaping steps.',
    '// dlog accumulates log of the scale factor, i.e. the growth of cosh(d(0,z)).',
    'P2 stepKlein(P2 k, int i, out float dlog){',
    '  P3 V = hvert(i);',
    '  if (uGeom != 0){',
    '    dlog = 0.0;',
    '    return P2(RSUB(RADD(V.x, V.x), k.x), RSUB(RADD(V.y, V.y), k.y));',
    '  }',
    '  REAL a = RSUB(RADD(RMUL(k.x, V.x), RMUL(k.y, V.y)), V.z);',
    '  REAL a2 = RADD(a, a);',
    '  REAL yx = RNEG(RADD(k.x, RMUL(a2, V.x)));',
    '  REAL yy = RNEG(RADD(k.y, RMUL(a2, V.y)));',
    '  REAL yz = RNEG(RADD(RC(1.0), RMUL(a2, V.z)));',
    '  dlog = log(max(RF(yz), 1e-30));',
    '  return P2(RDIV(yx, yz), RDIV(yy, yz));',
    '}',
    '',
    '// The support vertex. Seen from a point outside a convex table the vertices are',
    '// angularly unimodal, so hill-climbing from the previous step finds the same vertex as a',
    '// full scan in O(1): consecutive orbit points usually share it or move one place along.',
    'int supportVertex(P2 kp, int start){',
    '  int b = start;',
    '  for (int g = 0; g < MAXV; g++){',
    '    if (g >= uN) break;',
    '    int nx = b + 1; if (nx >= uN) nx = 0;',
    '    int pv = b - 1; if (pv < 0) pv = uN - 1;',
    '    P2 cb = subP(kvert(b), kp);',
    '    if (RLT0(crsP(cb, subP(kvert(nx), kp)))) { b = nx; continue; }',
    '    if (RLT0(crsP(cb, subP(kvert(pv), kp)))) { b = pv; continue; }',
    '    break;',
    '  }',
    '  return b;',
    '}',
    '',
    '// Second most clockwise vertex; a tie with the support vertex means the tangent line',
    '// contains a whole edge, which is exactly the singular set of the map.',
    'int runnerUp(P2 kp, int best){',
    '  int runner = -1;',
    '  for (int j = 0; j < MAXV; j++){',
    '    if (j >= uN) break;',
    '    if (j == best) continue;',
    '    if (runner < 0 || RLT0(crsP(subP(kvert(j), kp), subP(kvert(runner), kp)))) runner = j;',
    '  }',
    '  return runner < 0 ? best : runner;',
    '}',
    '',
    '// Distance from the orbit point to the geodesic spanned by two vertices. In the disk this',
    '// is sinh of the hyperbolic distance, via the Minkowski normal of the plane through them.',
    '// The cancelling subtraction is done at full precision, the rest in float.',
    'float singDistance(P2 k, int ia, int ib){',
    '  P3 A = hvert(ia), B = hvert(ib);',
    '  vec2 kf = toF(k);',
    '  if (uGeom != 0){',
    '    vec2 e = vec2(RF(RSUB(B.x, A.x)), RF(RSUB(B.y, A.y)));',
    '    REAL num = RSUB(RMUL(RC(e.x), RSUB(k.y, A.y)), RMUL(RC(e.y), RSUB(k.x, A.x)));',
    '    return abs(RF(num)) / max(length(e), 1e-20);',
    '  }',
    '  vec3 af = vec3(RF(A.x), RF(A.y), RF(A.z));',
    '  vec3 bf = vec3(RF(B.x), RF(B.y), RF(B.z));',
    '  vec3 c = cross(af, bf);',
    '  vec3 N = vec3(c.x, c.y, -c.z);',
    '  float nn = N.x*N.x + N.y*N.y - N.z*N.z;',
    '  REAL num = RSUB(RADD(RMUL(k.x, RC(N.x)), RMUL(k.y, RC(N.y))), RC(N.z));',
    '  float den = sqrt(max(nn, 1e-30)) * sqrt(max(1.0 - dot(kf, kf), 1e-30));',
    '  return abs(RF(num)) / den;',
    '}',
    '',
    'bool insideTable(P2 kp){',
    '  for (int j = 0; j < MAXV; j++){',
    '    if (j >= uN) break;',
    '    int n = j + 1; if (n >= uN) n = 0;',
    '    P2 a = kvert(j);',
    '    if (RLT0(crsP(subP(kvert(n), a), subP(kp, a)))) return false;',
    '  }',
    '  return true;',
    '}',
    '',
    '// Separation from the seed, measured in the Klein chart around the seed: monotone in',
    '// distance and well conditioned because the seed is always a visible on-screen point.',
    'float sepMeasure(P2 a, P2 b){',
    '  vec2 d = toF(subP(a, b));',
    '  if (uGeom != 0) return dot(d, d);',
    '  vec2 bf = toF(b);',
    '  float nb = max(1.0 - dot(bf, bf), 1e-20);',
    '  return dot(d, d) / (nb * nb);',
    '}',
    '',
    'vec3 orbitColor(P2 k){',
    '  P2 k0 = k, kCol = k;',
    '  vec2 kf = toF(k);',
    '  float smoothItin = 0.0, w = 0.5;',
    '  uint hash = 2166136261u;',
    '  int firstSym = 0, pickSym = 0, period = 0, done = 0, prevBest = 0;',
    '  // L = log cosh d(0, z), which stays finite however far the orbit escapes',
    '  float L = uGeom == 0 ? -0.5 * log(max(1.0 - dot(kf,kf), 1e-30)) : 0.0;',
    '  float maxL = L, maxR2 = dot(kf,kf), dlog;',
    '  float sing = 1e30;',
    '',
    '  for (int it = 0; it < 1000; it++){',
    '    if (it >= uIters) break;',
    '    if (insideTable(k)) break;',
    '    int i = supportVertex(k, prevBest);',
    '    prevBest = i;',
    '    if (uGlow > 0.0) sing = min(sing, singDistance(k, i, runnerUp(k, i)));',
    '    if (it == 0) firstSym = i;',
    '    if (uMode == 0){ smoothItin += w * (float(i) + 0.5) / float(uN); w *= 0.5; }',
    '    hash = (hash ^ uint(i + 1)) * 16777619u;',
    '    if (uMode == 4 && it == uStepPick - 1) pickSym = i;',
    '    k = stepKlein(k, i, dlog);',
    '    kCol = k;',
    '    kf = toF(k);',
    '    if (!(dot(kf,kf) < 1e24)) break;',
    '    if (uMode == 5){ L += dlog; maxL = max(maxL, L); maxR2 = max(maxR2, dot(kf,kf)); }',
    '    done = it + 1;',
    '    if (uMode == 2){',
    '      if (period == 0 && sepMeasure(k, k0) < uEps) period = it + 1;',
    '      if (period != 0) break;',
    '    }',
    '  }',
    '',
    '  float hue = 0.0, sat = uSat, val = uVal;',
    '',
    '  // Restricted to one cell the map is a fixed isometry, so the start-to-finish',
    '  // displacement varies smoothly across the cell: a gradient per cell.',
    '  if (uShade > 0.0){',
    '    float r = sqrt(max(sepMeasure(kCol, k0), 0.0));',
    '    float d = uGeom != 0 ? r : log(r + sqrt(1.0 + r*r));',
    '    float t = abs(fract(d * uShadeScale) * 2.0 - 1.0);',
    '    val *= mix(1.0, 0.4 + 0.85 * t, uShade);',
    '  }',
    '',
    '  if (uMode == 0){',
    '    // the itinerary read as a base-N expansion; hue scale zooms into deeper symbols',
    '    hue = fract(smoothItin / max(uCScale, 0.005));',
    '  } else if (uMode == 1){',
    '    hue = float(hash & 0xffffffu) / 16777215.0;',
    '  } else if (uMode == 2){',
    '    if (period == 0){ return vec3(0.07, 0.08, 0.11) * uVal; }',
    '    hue = fract(float(period) * uCScale);',
    '    val *= 0.55 + 0.45 * fract(float(period) * 0.11);',
    '  } else if (uMode == 3){',
    '    hue = (float(firstSym) + 0.5) / float(uN);',
    '  } else if (uMode == 4){',
    '    if (done < uStepPick) { return vec3(0.07, 0.08, 0.11) * uVal; }',
    '    hue = (float(pickSym) + 0.5) / float(uN);',
    '  } else if (uMode == 5){',
    '    // acosh(exp(L)), written so that it stays exact for large L',
    '    float r = uGeom == 0 ? maxL + log(1.0 + sqrt(max(0.0, 1.0 - exp(-2.0*maxL))))',
    '                         : sqrt(maxR2);',
    '    hue = fract(r * uCScale);',
    '    val *= 0.45 + 0.55 * fract(r * uCScale * 0.5 + 0.25);',
    '  } else {',
    '    float d = log(1.0 + sepMeasure(kCol, k0));',
    '    hue = fract(d * uCScale);',
    '  }',
    '',
    '  vec3 col = hsv2rgb(vec3(fract(hue + uHueShift), sat, val));',
    '  if (uGlow > 0.0){',
    '    col += uGlow * exp(-sing / max(uGlowW, 1e-5)) * (1.0 - 0.45 * col);',
    '  }',
    '  return col;',
    '}',
    '',
    'vec3 shade(P2 z){',
    '  vec2 zf = toF(z);',
    '  if (uGeom == 0 && dot(zf,zf) >= 1.0) return uBg;',
    '  P2 k = proj(z);',
    '  if (insideTable(k)) return uTable;',
    '  return orbitColor(k);',
    '}',
    '',
    'void main(){',
    '  vec3 acc = vec3(0.0);',
    '  float n = float(uSS);',
    '  for (int sy = 0; sy < 4; sy++){',
    '    if (sy >= uSS) break;',
    '    for (int sx = 0; sx < 4; sx++){',
    '      if (sx >= uSS) break;',
    '      vec2 off = (vec2(float(sx), float(sy)) + uJitter) / n;',
    '      acc += shade(pixelPoint(gl_FragCoord.xy - vec2(0.5) + off));',
    '    }',
    '  }',
    '  fragColor = vec4(clamp(acc / (n*n), 0.0, 1.0), 1.0);',
    '}'
    ].join('\n');
  }

  // resolves the accumulation buffer: the mean of all jittered passes
  var PRESENT = [
    '#version 300 es',
    'precision highp float;',
    'uniform sampler2D uAcc;',
    'uniform float uPasses;',
    'out vec4 fragColor;',
    'void main(){',
    '  vec3 c = texelFetch(uAcc, ivec2(gl_FragCoord.xy), 0).rgb / uPasses;',
    '  fragColor = vec4(clamp(c, 0.0, 1.0), 1.0);',
    '}'
  ].join('\n');

  return { VERT: VERT, FRAG: frag(false), FRAG_DEEP: frag(true), PRESENT: PRESENT, MAXV: 16 };
})();
