var SHADERS = (function () {
  'use strict';

  var VERT = [
    '#version 300 es',
    'in vec2 aPos;',
    'void main(){ gl_Position = vec4(aPos, 0.0, 1.0); }'
  ].join('\n');

  var FRAG = [
    '#version 300 es',
    'precision highp float;',
    'precision highp int;',
    'out vec4 fragColor;',
    '',
    '#define MAXV 16',
    'uniform vec2  uVerts[MAXV];   // Poincare coordinates',
    'uniform vec2  uKVerts[MAXV];  // Klein coordinates (CCW)',
    'uniform int   uN;',
    'uniform int   uGeom;          // 0 = Poincare disk, 1 = Euclidean plane',
    'uniform int   uIters;',
    'uniform int   uMode;',
    'uniform int   uStepPick;',
    'uniform int   uSS;',
    'uniform vec2  uCenter;',
    'uniform float uScale;         // disk units per device pixel',
    'uniform vec2  uResolution;',
    'uniform float uHueShift;',
    'uniform float uCScale;',
    'uniform float uSat;',
    'uniform float uVal;',
    'uniform float uEps;',
    'uniform vec3  uBg;',
    'uniform vec3  uTable;',
    '',
    'vec2 cmul(vec2 a, vec2 b){ return vec2(a.x*b.x - a.y*b.y, a.x*b.y + a.y*b.x); }',
    'vec2 cdiv(vec2 a, vec2 b){ float d = dot(b,b); return vec2(dot(a,b), a.y*b.x - a.x*b.y) / d; }',
    'vec2 toKlein(vec2 z){ return 2.0*z / (1.0 + dot(z,z)); }',
    'float crs(vec2 a, vec2 b){ return a.x*b.y - a.y*b.x; }',
    '',
    'vec3 hsv2rgb(vec3 c){',
    '  vec3 p = abs(fract(c.xxx + vec3(1.0, 2.0/3.0, 1.0/3.0)) * 6.0 - 3.0);',
    '  return c.z * mix(vec3(1.0), clamp(p - 1.0, 0.0, 1.0), c.y);',
    '}',
    '',
    '// rotation by pi about v',
    'vec2 reflectPoint(vec2 z, vec2 v){',
    '  float s = 1.0 + dot(v,v);',
    '  vec2 num = 2.0*v - s*z;',
    '  vec2 den = vec2(s, 0.0) - 2.0*cmul(vec2(v.x, -v.y), z);',
    '  return cdiv(num, den);',
    '}',
    '',
    '// Klein projection: identity in the Euclidean model',
    'vec2 proj(vec2 z){ return uGeom == 0 ? toKlein(z) : z; }',
    '',
    '// one step of the outer billiard map: point reflection through v',
    'vec2 mapPoint(vec2 z, vec2 v){ return uGeom == 0 ? reflectPoint(z, v) : 2.0*v - z; }',
    '',
    'int supportVertex(vec2 kp){',
    '  int best = 0;',
    '  for (int j = 1; j < MAXV; j++){',
    '    if (j >= uN) break;',
    '    if (crs(uKVerts[best] - kp, uKVerts[j] - kp) < 0.0) best = j;',
    '  }',
    '  return best;',
    '}',
    '',
    'bool insideTable(vec2 kp){',
    '  for (int j = 0; j < MAXV; j++){',
    '    if (j >= uN) break;',
    '    int k = j + 1; if (k >= uN) k = 0;',
    '    if (crs(uKVerts[k] - uKVerts[j], kp - uKVerts[j]) < 0.0) return false;',
    '  }',
    '  return true;',
    '}',
    '',
    '// cosh(d)-1 in the disk, plain squared distance in the plane: both monotone in distance',
    'float sepMeasure(vec2 a, vec2 b){',
    '  if (uGeom != 0) return dot(a-b, a-b);',
    '  float na = max(1.0 - dot(a,a), 1e-20);',
    '  float nb = max(1.0 - dot(b,b), 1e-20);',
    '  return 2.0 * dot(a-b, a-b) / (na * nb);',
    '}',
    '',
    'bool escapes(vec2 z){',
    '  float q = dot(z,z);',
    '  return uGeom == 0 ? !(q < 0.9999999) : !(q < 1e12);',
    '}',
    '',
    'float radiusOf(float q){',
    '  return uGeom == 0 ? 2.0 * atanh(sqrt(clamp(q, 0.0, 0.99999999))) : sqrt(q);',
    '}',
    '',
    'vec3 orbitColor(vec2 z0){',
    '  vec2 z = z0;',
    '  float smoothItin = 0.0, w = 0.5;',
    '  uint hash = 2166136261u;',
    '  int firstSym = 0, pickSym = 0, period = 0, done = 0;',
    '  float maxR = dot(z0,z0);',
    '  bool escaped = false;',
    '',
    '  for (int k = 0; k < 512; k++){',
    '    if (k >= uIters) break;',
    '    vec2 kp = proj(z);',
    '    if (insideTable(kp)) { escaped = true; break; }',
    '    int i = supportVertex(kp);',
    '    if (k == 0) firstSym = i;',
    '    if (k == uStepPick - 1) pickSym = i;',
    '    smoothItin += w * (float(i) + 0.5) / float(uN);',
    '    w *= 0.5;',
    '    hash = (hash ^ uint(i + 1)) * 16777619u;',
    '    z = mapPoint(z, uVerts[i]);',
    '    done = k + 1;',
    '    if (escapes(z)) { escaped = true; break; }',
    '    maxR = max(maxR, dot(z,z));',
    '    if (period == 0 && sepMeasure(z, z0) < uEps) period = k + 1;',
    '    if (period != 0 && uMode == 2) break;',
    '  }',
    '',
    '  float hue = 0.0, sat = uSat, val = uVal;',
    '',
    '  if (uMode == 0){',
    '    // the itinerary read as a base-N expansion; hue scale zooms into deeper symbols',
    '    hue = fract(smoothItin / max(uCScale, 0.005));',
    '  } else if (uMode == 1){',
    '    hue = float(hash & 0xffffffu) / 16777215.0;',
    '  } else if (uMode == 2){',
    '    if (period == 0){ return vec3(0.07, 0.08, 0.11) * uVal; }',
    '    hue = fract(float(period) * uCScale);',
    '    val *= 0.55 + 0.45 * fract(float(period) * 0.11);',
    '  } else if (uMode == 3){',
    '    hue = (float(firstSym) + 0.5) / float(uN);',
    '  } else if (uMode == 4){',
    '    if (done < uStepPick) { return vec3(0.07, 0.08, 0.11) * uVal; }',
    '    hue = (float(pickSym) + 0.5) / float(uN);',
    '  } else if (uMode == 5){',
    '    float r = radiusOf(maxR);',
    '    hue = fract(r * uCScale);',
    '    val *= 0.45 + 0.55 * fract(r * uCScale * 0.5 + 0.25);',
    '  } else {',
    '    float d = log(1.0 + sepMeasure(z, z0));',
    '    hue = fract(d * uCScale);',
    '  }',
    '',
    '  if (escaped) { sat *= 0.35; val *= 0.55; }',
    '  return hsv2rgb(vec3(fract(hue + uHueShift), sat, val));',
    '}',
    '',
    'vec3 shade(vec2 z){',
    '  if (uGeom == 0 && dot(z,z) >= 1.0) return uBg;',
    '  if (insideTable(proj(z))) return uTable;',
    '  return orbitColor(z);',
    '}',
    '',
    'void main(){',
    '  vec3 acc = vec3(0.0);',
    '  float n = float(uSS);',
    '  for (int sy = 0; sy < 4; sy++){',
    '    if (sy >= uSS) break;',
    '    for (int sx = 0; sx < 4; sx++){',
    '      if (sx >= uSS) break;',
    '      vec2 off = (vec2(float(sx), float(sy)) + 0.5) / n;',
    '      vec2 p = gl_FragCoord.xy - vec2(0.5) + off;',
    '      vec2 z = uCenter + (p - 0.5 * uResolution) * uScale;',
    '      acc += shade(z);',
    '    }',
    '  }',
    '  fragColor = vec4(clamp(acc / (n*n), 0.0, 1.0), 1.0);',
    '}'
  ].join('\n');

  return { VERT: VERT, FRAG: FRAG, MAXV: 16 };
})();
