var SHADERS = (function () {
  'use strict';

  var VERT = [
    '#version 300 es',
    'in vec2 aPos;',
    'void main(){ gl_Position = vec4(aPos, 0.0, 1.0); }'
  ].join('\n');

  var FRAG = [
    '#version 300 es',
    'precision highp float;',
    'precision highp int;',
    'out vec4 fragColor;',
    '',
    '#define MAXV 16',
    'uniform vec2  uKVerts[MAXV];  // Klein coordinates (CCW)',
    'uniform vec3  uHVerts[MAXV];  // unit hyperboloid coordinates (Euclidean model: xy only)',
    'uniform int   uN;',
    'uniform int   uGeom;          // 0 = Poincare disk, 1 = Euclidean plane',
    'uniform int   uIters;',
    'uniform int   uMode;',
    'uniform int   uStepPick;',
    'uniform int   uSS;',
    'uniform vec2  uCenter;',
    'uniform float uScale;         // disk units per device pixel',
    'uniform vec2  uResolution;',
    'uniform float uHueShift;',
    'uniform float uCScale;',
    'uniform float uSat;',
    'uniform float uVal;',
    'uniform float uEps;',
    'uniform float uGlow;         // singular-set glow intensity',
    'uniform float uGlowW;        // glow width, in hyperbolic units',
    'uniform vec2  uJitter;        // sub-pixel offset of this pass',
    'uniform vec3  uBg;',
    'uniform vec3  uTable;',
    '',
    'vec2 toKlein(vec2 z){ return 2.0*z / (1.0 + dot(z,z)); }',
    'float crs(vec2 a, vec2 b){ return a.x*b.y - a.y*b.x; }',
    '',
    'vec3 hsv2rgb(vec3 c){',
    '  vec3 p = abs(fract(c.xxx + vec3(1.0, 2.0/3.0, 1.0/3.0)) * 6.0 - 3.0);',
    '  return c.z * mix(vec3(1.0), clamp(p - 1.0, 0.0, 1.0), c.y);',
    '}',
    '',
    '// Klein projection: identity in the Euclidean model',
    'vec2 proj(vec2 z){ return uGeom == 0 ? toKlein(z) : z; }',
    '',
    '// One step of the outer billiard map, in Klein coordinates.',
    '// Hyperbolic: the point reflection is the linear Lorentz map X -> -(X + 2<X,V>V) on the',
    '// hyperboloid, carried projectively as (k, 1). Being division-free it avoids the ruinous',
    '// cancellation of the Poincare formula, where 1-|z| underflows after ~20 escaping steps.',
    '// dlog accumulates log of the scale factor, i.e. the growth of cosh(d(0,z)).',
    'vec2 stepKlein(vec2 k, int i, out float dlog){',
    '  if (uGeom != 0){ dlog = 0.0; return 2.0*uHVerts[i].xy - k; }',
    '  vec3 V = uHVerts[i];',
    '  float a = k.x*V.x + k.y*V.y - V.z;',
    '  vec3 Y = -(vec3(k, 1.0) + 2.0*a*V);',
    '  dlog = log(max(Y.z, 1e-30));',
    '  return Y.xy / Y.z;',
    '}',
    '',
    '// The support vertex, plus the runner-up: a tie between the two means the tangent line',
    '// contains a whole edge, which is exactly the singular set of the map.',
    'int supportVertex(vec2 kp, out int runner){',
    '  int best = 0;',
    '  runner = 0;',
    '  bool haveRunner = false;',
    '  for (int j = 1; j < MAXV; j++){',
    '    if (j >= uN) break;',
    '    if (crs(uKVerts[best] - kp, uKVerts[j] - kp) < 0.0){',
    '      runner = best; best = j; haveRunner = true;',
    '    } else if (!haveRunner || crs(uKVerts[j] - kp, uKVerts[runner] - kp) < 0.0){',
    '      runner = j; haveRunner = true;',
    '    }',
    '  }',
    '  return best;',
    '}',
    '',
    '// Distance from the orbit point to the geodesic spanned by two vertices. In the disk this',
    '// is sinh of the hyperbolic distance, via the Minkowski normal of the plane through them.',
    'float singDistance(vec2 k, vec3 A, vec3 B){',
    '  if (uGeom != 0){',
    '    vec2 e = B.xy - A.xy;',
    '    return abs(crs(e, k - A.xy)) / max(length(e), 1e-20);',
    '  }',
    '  vec3 c = cross(A, B);',
    '  vec3 N = vec3(c.x, c.y, -c.z);',
    '  float nn = N.x*N.x + N.y*N.y - N.z*N.z;',
    '  float num = abs(k.x*N.x + k.y*N.y - N.z);',
    '  float den = sqrt(max(nn, 1e-30)) * sqrt(max(1.0 - dot(k,k), 1e-30));',
    '  return num / den;',
    '}',
    '',
    'bool insideTable(vec2 kp){',
    '  for (int j = 0; j < MAXV; j++){',
    '    if (j >= uN) break;',
    '    int k = j + 1; if (k >= uN) k = 0;',
    '    if (crs(uKVerts[k] - uKVerts[j], kp - uKVerts[j]) < 0.0) return false;',
    '  }',
    '  return true;',
    '}',
    '',
    '// Separation from the seed, measured in the Klein chart around the seed: monotone in',
    '// distance and well conditioned because the seed is always a visible on-screen point.',
    'float sepMeasure(vec2 a, vec2 b){',
    '  if (uGeom != 0) return dot(a-b, a-b);',
    '  float nb = max(1.0 - dot(b,b), 1e-20);',
    '  return dot(a-b, a-b) / (nb * nb);',
    '}',
    '',
    'vec3 orbitColor(vec2 z0){',
    '  vec2 k = proj(z0), k0 = k;',
    '  float smoothItin = 0.0, w = 0.5;',
    '  uint hash = 2166136261u;',
    '  int firstSym = 0, pickSym = 0, period = 0, done = 0;',
    '  // L = log cosh d(0, z), which stays finite however far the orbit escapes',
    '  float L = uGeom == 0 ? -0.5 * log(max(1.0 - dot(k,k), 1e-30)) : 0.0;',
    '  float maxL = L, maxR2 = dot(k,k), dlog;',
    '  float sing = 1e30;',
    '',
    '  for (int it = 0; it < 512; it++){',
    '    if (it >= uIters) break;',
    '    if (insideTable(k)) break;',
    '    int runner;',
    '    int i = supportVertex(k, runner);',
    '    if (uGlow > 0.0) sing = min(sing, singDistance(k, uHVerts[i], uHVerts[runner]));',
    '    if (it == 0) firstSym = i;',
    '    if (it == uStepPick - 1) pickSym = i;',
    '    smoothItin += w * (float(i) + 0.5) / float(uN);',
    '    w *= 0.5;',
    '    hash = (hash ^ uint(i + 1)) * 16777619u;',
    '    k = stepKlein(k, i, dlog);',
    '    if (!(dot(k,k) < 1e24)) break;',
    '    L += dlog;',
    '    maxL = max(maxL, L);',
    '    maxR2 = max(maxR2, dot(k,k));',
    '    done = it + 1;',
    '    if (period == 0 && sepMeasure(k, k0) < uEps) period = it + 1;',
    '    if (period != 0 && uMode == 2) break;',
    '  }',
    '',
    '  float hue = 0.0, sat = uSat, val = uVal;',
    '',
    '  if (uMode == 0){',
    '    // the itinerary read as a base-N expansion; hue scale zooms into deeper symbols',
    '    hue = fract(smoothItin / max(uCScale, 0.005));',
    '  } else if (uMode == 1){',
    '    hue = float(hash & 0xffffffu) / 16777215.0;',
    '  } else if (uMode == 2){',
    '    if (period == 0){ return vec3(0.07, 0.08, 0.11) * uVal; }',
    '    hue = fract(float(period) * uCScale);',
    '    val *= 0.55 + 0.45 * fract(float(period) * 0.11);',
    '  } else if (uMode == 3){',
    '    hue = (float(firstSym) + 0.5) / float(uN);',
    '  } else if (uMode == 4){',
    '    if (done < uStepPick) { return vec3(0.07, 0.08, 0.11) * uVal; }',
    '    hue = (float(pickSym) + 0.5) / float(uN);',
    '  } else if (uMode == 5){',
    '    // acosh(exp(L)), written so that it stays exact for large L',
    '    float r = uGeom == 0 ? maxL + log(1.0 + sqrt(max(0.0, 1.0 - exp(-2.0*maxL))))',
    '                         : sqrt(maxR2);',
    '    hue = fract(r * uCScale);',
    '    val *= 0.45 + 0.55 * fract(r * uCScale * 0.5 + 0.25);',
    '  } else {',
    '    float d = log(1.0 + sepMeasure(k, k0));',
    '    hue = fract(d * uCScale);',
    '  }',
    '',
    '  vec3 col = hsv2rgb(vec3(fract(hue + uHueShift), sat, val));',
    '  if (uGlow > 0.0){',
    '    col += uGlow * exp(-sing / max(uGlowW, 1e-5)) * (1.0 - 0.45 * col);',
    '  }',
    '  return col;',
    '}',
    '',
    'vec3 shade(vec2 z){',
    '  if (uGeom == 0 && dot(z,z) >= 1.0) return uBg;',
    '  if (insideTable(proj(z))) return uTable;',
    '  return orbitColor(z);',
    '}',
    '',
    'void main(){',
    '  vec3 acc = vec3(0.0);',
    '  float n = float(uSS);',
    '  for (int sy = 0; sy < 4; sy++){',
    '    if (sy >= uSS) break;',
    '    for (int sx = 0; sx < 4; sx++){',
    '      if (sx >= uSS) break;',
    '      vec2 off = (vec2(float(sx), float(sy)) + uJitter) / n;',
    '      vec2 p = gl_FragCoord.xy - vec2(0.5) + off;',
    '      vec2 z = uCenter + (p - 0.5 * uResolution) * uScale;',
    '      acc += shade(z);',
    '    }',
    '  }',
    '  fragColor = vec4(clamp(acc / (n*n), 0.0, 1.0), 1.0);',
    '}'
  ].join('\n');

  // resolves the accumulation buffer: the mean of all jittered passes
  var PRESENT = [
    '#version 300 es',
    'precision highp float;',
    'uniform sampler2D uAcc;',
    'uniform float uPasses;',
    'out vec4 fragColor;',
    'void main(){',
    '  vec3 c = texelFetch(uAcc, ivec2(gl_FragCoord.xy), 0).rgb / uPasses;',
    '  fragColor = vec4(clamp(c, 0.0, 1.0), 1.0);',
    '}'
  ].join('\n');

  return { VERT: VERT, FRAG: FRAG, PRESENT: PRESENT, MAXV: 16 };
})();
